---
title: "Mgmt 123: Managerial economics"
---

<br>

**Class schedule:** Monday & Tuesday \| 17:00 - 18:00 <br> **Laboratory schedule:** Wednesday \| 16:00 - 19:00 <br> **Instructor:** Christopher Llones <br> **e-mail:** christopher.llones\@vsu.edu.ph <br> **Pre-requisites:** Econ 115 - Econometrics <br> **Course credits:** 3 units <br> **Number of hours:** 2 hrs lectures and 3 hrs laboratory per week <br>

------------------------------------------------------------------------

### Course description

Introduction to survey research and survey data analysis using R programming.

### Course objectives

-   Create a valid and reliable survey questionnaire and survey codebook.
-   Perform exploratory data analysis on survey data using R programming.
-   Perform Parametric and Non-Parametric Test on Means using R.
-   Perform correlation analysis and build a regression model explaining relationship of certain economic variables in R.
-   Perform regression analysis on limited dependent variables in R.
-   Perform various techniques of multivariate data analysis in the R statistical software.

### Course outline

+------------+-----------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week       | Topics                                        | Lessons                                           | Description                                                                                                                                                                                                                          |
+============+===============================================+===================================================+======================================================================================================================================================================================================================================+
| Week 2-4   | Module 1: survey research design              | 1.  Methods of data collection                    | 1.  Discuss the various methods of data collection including survey, observation and experimental methods.                                                                                                                           |
|            |                                               | 2.  Sampling design in surveys                    | 2.  Discuss different ways for gathering a sample; random and non-random sampling. Discuss rudimentary formulas for sample size calculation.                                                                                         |
|            |                                               | 3.  Measurement issues in survey research         | 3.  Discuss the issues in assigning numbers to represent quantities of attributes. Discuss the various scales of measurement. Discuss criteria in constructing good measurement of variables: reliablity and validity.               |
|            |                                               | 4.  Questionnaire construction                    | 4.  Discuss the various advantages and disadvantages of interviews and questionnaire over other methods of data collection.                                                                                                          |
|            |                                               | 5.  Basics of interviewing                        | 5.  Discuss the do's and dont's of an interviewer's conduct.                                                                                                                                                                         |
|            |                                               | 6.  Creating a codebook                           | 6.  Discuss the importance of creating a codebook for survey data.                                                                                                                                                                   |
|            |                                               | 7.  Data entry                                    | 7.  Discuss rudimentary of data entry.                                                                                                                                                                                               |
+------------+-----------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 5-6   | Module 2: exploratory data analysis           | 1.  Rudiments of EDA                              | 1.  Discuss EDA as the first step in data analysis.                                                                                                                                                                                  |
|            |                                               | 2.  Charts and tables                             | 2.  Discuss various techniques in summarizing and visualizing data.                                                                                                                                                                  |
|            |                                               | 3.  Measures of central tendency                  | 3.  Discuss the various measures of central tendency and data location.                                                                                                                                                              |
|            |                                               | 4.  Dispersion, parameters, skewness and kurtosis | 4.  Discuss the relevance of various dispersion, parameters, skewness and kurtosis.                                                                                                                                                  |
|            |                                               | 5.  Contingency tables and scatter plot           | 5.  Discuss the relevance of contingency tables and scatterplots for summarizing and visualizing data.                                                                                                                               |
+------------+-----------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 7-8   | Module 3: test on means                       | 1.  Parametric test on means                      | 1.  Discuss the various t-tests and ANOVA and perform them on a sample data with R.                                                                                                                                                  |
|            |                                               | 2.  Non-parametric test on means                  | 2.  Perform various non-parametric equivalent of the t-tests and ANOVA on sample data with R.                                                                                                                                        |
+------------+-----------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 9-11  | Module 4: correlation and regression analysis | 1.  Correlation analysis                          | 1.  Discuss the various types of correlation analysis procedures. Interpret the correlation coefficient.                                                                                                                             |
|            |                                               | 2.  Review of Regression analysis                 | 2.  Discuss the various aspects of regression model building.                                                                                                                                                                        |
+------------+-----------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 12-15 | Module 5: limited-dependent variable models   | 1.  Review of binary dependent regression         | 1.  Discuss the various aspects of the logit and probit.                                                                                                                                                                             |
|            |                                               | 2.  Extension to the logit model.                 | 2.  Discuss the multinomial and ordinal logit models.                                                                                                                                                                                |
|            |                                               | 3.  Censored and truncated regression models.     | 3.  Discuss the Tobit regression model for censored data and truncated regression models.                                                                                                                                            |
|            |                                               | 4.  Count dependent variable models.              | 4.  Discuss Poisson and Negative Binomial regression models in the regression analysis of count-dependent variable models.                                                                                                           |
+------------+-----------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 16-17 | Module 6: multivariate statistical analysis   | 1.  Cluster analysis                              | 1.  Understand and apply different clustering methods. Analyze and evaluate the quality and effectiveness of different clusters in dataset.                                                                                          |
|            |                                               | 2.  Principal component analysis                  | 2.  Learn to perform and interpret principal component analysis to reduce the dimensionality of dataset. Develop the ability to identify and retain significant components for simplifying data without losing critical information. |
|            |                                               | 3.  Exploratory factor analysis                   | 3.  Identify and estimate underlying factor structures within a set of observed variables.                                                                                                                                           |
|            |                                               | 4.  Confirmatory factor anlysis                   | 4.  Understand model-based factor anlaysis and develop proficiency in evaluating model fit and making necessary adjustments to improve analysis.                                                                                     |
|            |                                               | 5.  Structural equation modelling                 | 5.  Apply SEM techniques to understand relationships among variables and construct theoretical models.                                                                                                                               |
+------------+-----------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
